"""workout session completed flag

Revision ID: 16b790bd0d6c
Revises: 9b00087b216f
Create Date: 2026-08-24 23:15:36.280711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b790bd0d6c'
down_revision: Union[str, None] = '9b00087b216f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default para poder añadir la columna NOT NULL sobre sesiones ya
    # existentes en producción: las anteriores se marcan como completadas
    # (son entrenos ya registrados, no borradores a medias). El default a nivel
    # de BD es inocuo: la app siempre envía `completed` explícito al insertar.
    op.add_column(
        "workout_sessions",
        sa.Column("completed", sa.Boolean(), nullable=False, server_default=sa.true()),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_sessions', 'completed')
    # ### end Alembic commands ###
