"""admin flag on users

Revision ID: 9b00087b216f
Revises: b1861c6d332e
Create Date: 2026-07-21 14:01:26.299180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b00087b216f'
down_revision: Union[str, None] = 'b1861c6d332e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default para que la columna NOT NULL pueda añadirse sobre una
    # tabla que ya tiene filas (producción).
    op.add_column(
        "users",
        sa.Column("is_admin", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # Backfill: el primer usuario registrado de la instancia (id mínimo) es el
    # dueño del despliegue -> admin. Los registros nuevos lo fijan en código.
    op.execute("UPDATE users SET is_admin = TRUE WHERE id = (SELECT MIN(id) FROM users)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
