"""planned workouts

Revision ID: fcaf889cd709
Revises: 16b790bd0d6c
Create Date: 2026-08-25 11:15:34.413394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcaf889cd709'
down_revision: Union[str, None] = '16b790bd0d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planned_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('workout_type', sa.Enum('GYM1', 'GYM2', 'GYM3', 'RUNNING', 'CUSTOM', name='workouttype', native_enum=False), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_planned_user_date')
    )
    op.create_index(op.f('ix_planned_workouts_date'), 'planned_workouts', ['date'], unique=False)
    op.create_index(op.f('ix_planned_workouts_user_id'), 'planned_workouts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planned_workouts_user_id'), table_name='planned_workouts')
    op.drop_index(op.f('ix_planned_workouts_date'), table_name='planned_workouts')
    op.drop_table('planned_workouts')
    # ### end Alembic commands ###
